# UNCLASSIFIED
default namespace = "urn:us:gov:ic:cvenum:usagency:usgovagencyacronym"
CVEnumUSGOVAgencyAcronym.cve = 
# (U) 
"USA.ABMC" | 
# (U) 
"USA.ACCESS" | 
# (U) 
"USA.ACFR" | 
# (U) 
"USA.ACHP" | 
# (U) 
"USA.ACUS" | 
# (U) 
"USA.ADF" | 
# (U) 
"USA.AMICC" | 
# (U) 
"USA.AMTRAK" | 
# (U) 
"USA.ARC" | 
# (U) 
"USA.ARCTIC" | 
# (U) 
"USA.BBG" | 
# (U) 
"USA.BMGS" | 
# (U) 
"USA.CAOC" | 
# (U) 
"USA.CCJJ" | 
# (U) 
"USA.CCR" | 
# (U) 
"USA.CEA" | 
# (U) 
"USA.CFA" | 
# (U) 
"USA.CFI" | 
# (U) 
"USA.CFOC" | 
# (U) 
"USA.CFTC" | 
# (U) 
"USA.CHCOC" | 
# (U) 
"USA.CIA" | 
# (U) 
"USA.CIOC" | 
# (U) 
"USA.CIRF" | 
# (U) 
"USA.CITA" | 
# (U) 
"USA.CNCS" | 
# (U) 
"USA.COMP" | 
# (U) 
"USA.CPSC" | 
# (U) 
"USA.CSAC" | 
# (U) 
"USA.CSHIB" | 
# (U) 
"USA.CSOSA" | 
# (U) 
"USA.DEA" | 
# (U) 
"USA.DENALI" | 
# (U) 
"USA.DFC" | 
# (U) 
"USA.DHS" | 
# (U) 
"USA.DIA" | 
# (U) 
"USA.DNFSB" | 
# (U) 
"USA.DNI" | 
# (U) 
"USA.DOC" | 
# (U) 
"USA.DOD" | 
# (U) 
"USA.DOE" | 
# (U) 
"USA.DOI" | 
# (U) 
"USA.DOJ" | 
# (U) 
"USA.DOL" | 
# (U) 
"USA.DOT" | 
# (U) 
"USA.DRBC" | 
# (U) 
"USA.EAC" | 
# (U) 
"USA.ED" | 
# (U) 
"USA.EEOC" | 
# (U) 
"USA.EIBUS" | 
# (U) 
"USA.EOP" | 
# (U) 
"USA.EPA" | 
# (U) 
"USA.ESC" | 
# (U) 
"USA.FAC" | 
# (U) 
"USA.FASAB" | 
# (U) 
"USA.FBI" | 
# (U) 
"USA.FCA" | 
# (U) 
"USA.FCC" | 
# (U) 
"USA.FCIC" | 
# (U) 
"USA.FCSIC" | 
# (U) 
"USA.FDIC" | 
# (U) 
"USA.FEB" | 
# (U) 
"USA.FEC" | 
# (U) 
"USA.FERC" | 
# (U) 
"USA.FFB" | 
# (U) 
"USA.FFIEC" | 
# (U) 
"USA.FGDC" | 
# (U) 
"USA.FHRA" | 
# (U) 
"USA.FICE" | 
# (U) 
"USA.FICMNEW" | 
# (U) 
"USA.FICSP" | 
# (U) 
"USA.FLCTT" | 
# (U) 
"USA.FLICC" | 
# (U) 
"USA.FLRA" | 
# (U) 
"USA.FMC" | 
# (U) 
"USA.FMCS" | 
# (U) 
"USA.FMSHRC" | 
# (U) 
"USA.FRS" | 
# (U) 
"USA.FRTIB" | 
# (U) 
"USA.FTC" | 
# (U) 
"USA.GSA" | 
# (U) 
"USA.HELSINKI" | 
# (U) 
"USA.HHS" | 
# (U) 
"USA.HMM" | 
# (U) 
"USA.HSTSF" | 
# (U) 
"USA.HUD" | 
# (U) 
"USA.IACB" | 
# (U) 
"USA.IADRWG" | 
# (U) 
"USA.IAF" | 
# (U) 
"USA.IBB" | 
# (U) 
"USA.ICH" | 
# (U) 
"USA.ICPRB" | 
# (U) 
"USA.IMCNHCC" | 
# (U) 
"USA.IMLS" | 
# (U) 
"USA.ITC" | 
# (U) 
"USA.JBEA" | 
# (U) 
"USA.JFSP" | 
# (U) 
"USA.JMMFF" | 
# (U) 
"USA.JUSFC" | 
# (U) 
"USA.JWFFSB" | 
# (U) 
"USA.LSC" | 
# (U) 
"USA.MBCC" | 
# (U) 
"USA.MCC" | 
# (U) 
"USA.MKUF" | 
# (U) 
"USA.MMC" | 
# (U) 
"USA.MRC" | 
# (U) 
"USA.MSPB" | 
# (U) 
"USA.NARA" | 
# (U) 
"USA.NASA" | 
# (U) 
"USA.NBCFM" | 
# (U) 
"USA.NCD" | 
# (U) 
"USA.NCFRR" | 
# (U) 
"USA.NCPC" | 
# (U) 
"USA.NCUA" | 
# (U) 
"USA.NEA" | 
# (U) 
"USA.NEH" | 
# (U) 
"USA.NGA" | 
# (U) 
"USA.NIGC" | 
# (U) 
"USA.NLRB" | 
# (U) 
"USA.NMB" | 
# (U) 
"USA.NPF" | 
# (U) 
"USA.NPPC" | 
# (U) 
"USA.NRC" | 
# (U) 
"USA.NRO" | 
# (U) 
"USA.NSA" | 
# (U) 
"USA.NSF" | 
# (U) 
"USA.NTSB" | 
# (U) 
"USA.NWTRB" | 
# (U) 
"USA.OGE" | 
# (U) 
"USA.OMB" | 
# (U) 
"USA.ONCIX" | 
# (U) 
"USA.OPIC" | 
# (U) 
"USA.OPM" | 
# (U) 
"USA.OSC" | 
# (U) 
"USA.OSHRC" | 
# (U) 
"USA.OVP" | 
# (U) 
"USA.PBGC" | 
# (U) 
"USA.PCC" | 
# (U) 
"USA.PEACE" | 
# (U) 
"USA.PRC" | 
# (U) 
"USA.PRESIDIO" | 
# (U) 
"USA.RISC" | 
# (U) 
"USA.RRB" | 
# (U) 
"USA.SBA" | 
# (U) 
"USA.SEC" | 
# (U) 
"USA.SJI" | 
# (U) 
"USA.SMITH" | 
# (U) 
"USA.SRBC" | 
# (U) 
"USA.SSA" | 
# (U) 
"USA.SSAB" | 
# (U) 
"USA.SSS" | 
# (U) 
"USA.STATE" | 
# (U) 
"USA.TAP" | 
# (U) 
"USA.TDA" | 
# (U) 
"USA.TREAS" | 
# (U) 
"USA.TVA" | 
# (U) 
"USA.USA" | 
# (U) 
"USA.USAF" | 
# (U) 
"USA.USAID" | 
# (U) 
"USA.USAOC" | 
# (U) 
"USA.USCG" | 
# (U) 
"USA.USDA" | 
# (U) 
"USA.USIP" | 
# (U) 
"USA.USMC" | 
# (U) 
"USA.USN" | 
# (U) 
"USA.USPS" | 
# (U) 
"USA.USSF" | 
# (U) 
"USA.USTR" | 
# (U) 
"USA.USUN" | 
# (U) 
"USA.VA" | 
# (U) 
"USA.VDNC" | 
# (U) 
"USA.VEF" | 
# (U) 
"USA.WHCPS" | 
# (U) 
"USA.WHMO"
