package refdata

// CountryCodes returns the full set of country, coalition, organization, and
// marker codes from CVEnumISMCATOwnerProducer.xsd (version 202211, 341 entries).
// Includes the FGI marker, GENC trigraphs, and IC Markings System Register
// coalition/organization tetragraphs.
func CountryCodes() []CountryCode {
	return []CountryCode{
		// FGI marker
		{Code: "FGI", Name: "Foreign Government Information", Type: "marker"},

		// Countries and territories (GENC trigraphs)
		{Code: "ABW", Name: "Aruba", Type: "country"},
		{Code: "AFG", Name: "Islamic Republic of Afghanistan", Type: "country"},
		{Code: "AGO", Name: "Republic of Angola", Type: "country"},
		{Code: "AIA", Name: "Anguilla", Type: "country"},
		{Code: "ALB", Name: "Republic of Albania", Type: "country"},
		{Code: "AND", Name: "Principality of Andorra", Type: "country"},
		{Code: "ARE", Name: "United Arab Emirates", Type: "country"},
		{Code: "ARG", Name: "Argentine Republic", Type: "country"},
		{Code: "ARM", Name: "Republic of Armenia", Type: "country"},
		{Code: "ASM", Name: "Territory of American Samoa", Type: "country"},
		{Code: "ATA", Name: "Antarctica", Type: "country"},
		{Code: "ATF", Name: "French Southern and Antarctic Lands", Type: "country"},
		{Code: "ATG", Name: "Antigua and Barbuda", Type: "country"},
		{Code: "AUS", Name: "Commonwealth of Australia", Type: "country"},
		{Code: "AUT", Name: "Republic of Austria", Type: "country"},
		{Code: "AX2", Name: "Guantanamo Bay Naval Base", Type: "country"},
		{Code: "AX3", Name: "Entity 6", Type: "country"},
		{Code: "AZE", Name: "Republic of Azerbaijan", Type: "country"},
		{Code: "BDI", Name: "Republic of Burundi", Type: "country"},
		{Code: "BEL", Name: "Kingdom of Belgium", Type: "country"},
		{Code: "BEN", Name: "Republic of Benin", Type: "country"},
		{Code: "BES", Name: "Bonaire, Sint Eustatius, and Saba", Type: "country"},
		{Code: "BFA", Name: "Burkina Faso", Type: "country"},
		{Code: "BGD", Name: "People's Republic of Bangladesh", Type: "country"},
		{Code: "BGR", Name: "Republic of Bulgaria", Type: "country"},
		{Code: "BHR", Name: "Kingdom of Bahrain", Type: "country"},
		{Code: "BHS", Name: "Commonwealth of The Bahamas", Type: "country"},
		{Code: "BIH", Name: "Bosnia and Herzegovina", Type: "country"},
		{Code: "BLM", Name: "Saint Barthelemy", Type: "country"},
		{Code: "BLR", Name: "Republic of Belarus", Type: "country"},
		{Code: "BLZ", Name: "Belize", Type: "country"},
		{Code: "BMU", Name: "Bermuda", Type: "country"},
		{Code: "BOL", Name: "Plurinational State of Bolivia", Type: "country"},
		{Code: "BRA", Name: "Federative Republic of Brazil", Type: "country"},
		{Code: "BRB", Name: "Barbados", Type: "country"},
		{Code: "BRN", Name: "Brunei Darussalam", Type: "country"},
		{Code: "BTN", Name: "Kingdom of Bhutan", Type: "country"},
		{Code: "BVT", Name: "Bouvet Island", Type: "country"},
		{Code: "BWA", Name: "Republic of Botswana", Type: "country"},
		{Code: "CAF", Name: "Central African Republic", Type: "country"},
		{Code: "CAN", Name: "Canada", Type: "country"},
		{Code: "CCK", Name: "Territory of Cocos (Keeling) Islands", Type: "country"},
		{Code: "CHE", Name: "Swiss Confederation", Type: "country"},
		{Code: "CHL", Name: "Republic of Chile", Type: "country"},
		{Code: "CHN", Name: "People's Republic of China", Type: "country"},
		{Code: "CIV", Name: "Republic of Côte d'Ivoire", Type: "country"},
		{Code: "CMR", Name: "Republic of Cameroon", Type: "country"},
		{Code: "COD", Name: "Democratic Republic of the Congo", Type: "country"},
		{Code: "COG", Name: "Republic of the Congo", Type: "country"},
		{Code: "COK", Name: "Cook Islands", Type: "country"},
		{Code: "COL", Name: "Republic of Colombia", Type: "country"},
		{Code: "COM", Name: "Union of the Comoros", Type: "country"},
		{Code: "CPT", Name: "Clipperton Island", Type: "country"},
		{Code: "CPV", Name: "Republic of Cabo Verde", Type: "country"},
		{Code: "CRI", Name: "Republic of Costa Rica", Type: "country"},
		{Code: "CUB", Name: "Republic of Cuba", Type: "country"},
		{Code: "CUW", Name: "Curaçao", Type: "country"},
		{Code: "CXR", Name: "Territory of Christmas Island", Type: "country"},
		{Code: "CYM", Name: "Cayman Islands", Type: "country"},
		{Code: "CYP", Name: "Republic of Cyprus", Type: "country"},
		{Code: "CZE", Name: "Czech Republic", Type: "country"},
		{Code: "DEU", Name: "Federal Republic of Germany", Type: "country"},
		{Code: "DGA", Name: "Diego Garcia", Type: "country"},
		{Code: "DJI", Name: "Republic of Djibouti", Type: "country"},
		{Code: "DMA", Name: "Commonwealth of Dominica", Type: "country"},
		{Code: "DNK", Name: "Kingdom of Denmark", Type: "country"},
		{Code: "DOM", Name: "Dominican Republic", Type: "country"},
		{Code: "DZA", Name: "People's Democratic Republic of Algeria", Type: "country"},
		{Code: "ECU", Name: "Republic of Ecuador", Type: "country"},
		{Code: "EGY", Name: "Arab Republic of Egypt", Type: "country"},
		{Code: "ERI", Name: "State of Eritrea", Type: "country"},
		{Code: "ESH", Name: "Western Sahara", Type: "country"},
		{Code: "ESP", Name: "Kingdom of Spain", Type: "country"},
		{Code: "EST", Name: "Republic of Estonia", Type: "country"},
		{Code: "ETH", Name: "Federal Democratic Republic of Ethiopia", Type: "country"},
		{Code: "FIN", Name: "Republic of Finland", Type: "country"},
		{Code: "FJI", Name: "Republic of Fiji", Type: "country"},
		{Code: "FLK", Name: "Falkland Islands (Islas Malvinas)", Type: "country"},
		{Code: "FRA", Name: "French Republic", Type: "country"},
		{Code: "FRO", Name: "Faroe Islands", Type: "country"},
		{Code: "FSM", Name: "Federated States of Micronesia", Type: "country"},
		{Code: "GAB", Name: "Gabonese Republic", Type: "country"},
		{Code: "GBR", Name: "United Kingdom of Great Britain and Northern Ireland", Type: "country"},
		{Code: "GEO", Name: "Georgia", Type: "country"},
		{Code: "GGY", Name: "Bailiwick of Guernsey", Type: "country"},
		{Code: "GHA", Name: "Republic of Ghana", Type: "country"},
		{Code: "GIB", Name: "Gibraltar", Type: "country"},
		{Code: "GIN", Name: "Republic of Guinea", Type: "country"},
		{Code: "GLP", Name: "Region of Guadeloupe", Type: "country"},
		{Code: "GMB", Name: "Republic of The Gambia", Type: "country"},
		{Code: "GNB", Name: "Republic of Guinea-Bissau", Type: "country"},
		{Code: "GNQ", Name: "Republic of Equatorial Guinea", Type: "country"},
		{Code: "GRC", Name: "Hellenic Republic", Type: "country"},
		{Code: "GRD", Name: "Grenada", Type: "country"},
		{Code: "GRL", Name: "Greenland", Type: "country"},
		{Code: "GTM", Name: "Republic of Guatemala", Type: "country"},
		{Code: "GUF", Name: "Territorial Collectivity of Guiana", Type: "country"},
		{Code: "GUM", Name: "Territory of Guam", Type: "country"},
		{Code: "GUY", Name: "Co-operative Republic of Guyana", Type: "country"},
		{Code: "HKG", Name: "Hong Kong Special Administrative Region", Type: "country"},
		{Code: "HMD", Name: "Territory of Heard Island and McDonald Islands", Type: "country"},
		{Code: "HND", Name: "Republic of Honduras", Type: "country"},
		{Code: "HRV", Name: "Republic of Croatia", Type: "country"},
		{Code: "HTI", Name: "Republic of Haiti", Type: "country"},
		{Code: "HUN", Name: "Hungary", Type: "country"},
		{Code: "IDN", Name: "Republic of Indonesia", Type: "country"},
		{Code: "IMN", Name: "Isle of Man", Type: "country"},
		{Code: "IND", Name: "Republic of India", Type: "country"},
		{Code: "IOT", Name: "British Indian Ocean Territory", Type: "country"},
		{Code: "IRL", Name: "Ireland", Type: "country"},
		{Code: "IRN", Name: "Islamic Republic of Iran", Type: "country"},
		{Code: "IRQ", Name: "Republic of Iraq", Type: "country"},
		{Code: "ISL", Name: "Republic of Iceland", Type: "country"},
		{Code: "ISR", Name: "State of Israel", Type: "country"},
		{Code: "ITA", Name: "Italian Republic", Type: "country"},
		{Code: "JAM", Name: "Jamaica", Type: "country"},
		{Code: "JEY", Name: "Bailiwick of Jersey", Type: "country"},
		{Code: "JOR", Name: "Hashemite Kingdom of Jordan", Type: "country"},
		{Code: "JPN", Name: "Japan", Type: "country"},
		{Code: "KAZ", Name: "Republic of Kazakhstan", Type: "country"},
		{Code: "KEN", Name: "Republic of Kenya", Type: "country"},
		{Code: "KGZ", Name: "Kyrgyz Republic", Type: "country"},
		{Code: "KHM", Name: "Kingdom of Cambodia", Type: "country"},
		{Code: "KIR", Name: "Republic of Kiribati", Type: "country"},
		{Code: "KNA", Name: "Federation of Saint Kitts and Nevis", Type: "country"},
		{Code: "KOR", Name: "Republic of Korea", Type: "country"},
		{Code: "KWT", Name: "State of Kuwait", Type: "country"},
		{Code: "LAO", Name: "Lao People's Democratic Republic", Type: "country"},
		{Code: "LBN", Name: "Lebanese Republic", Type: "country"},
		{Code: "LBR", Name: "Republic of Liberia", Type: "country"},
		{Code: "LBY", Name: "State of Libya", Type: "country"},
		{Code: "LCA", Name: "Saint Lucia", Type: "country"},
		{Code: "LIE", Name: "Principality of Liechtenstein", Type: "country"},
		{Code: "LKA", Name: "Democratic Socialist Republic of Sri Lanka", Type: "country"},
		{Code: "LSO", Name: "Kingdom of Lesotho", Type: "country"},
		{Code: "LTU", Name: "Republic of Lithuania", Type: "country"},
		{Code: "LUX", Name: "Grand Duchy of Luxembourg", Type: "country"},
		{Code: "LVA", Name: "Republic of Latvia", Type: "country"},
		{Code: "MAC", Name: "Macau Special Administrative Region", Type: "country"},
		{Code: "MAF", Name: "Saint Martin", Type: "country"},
		{Code: "MAR", Name: "Kingdom of Morocco", Type: "country"},
		{Code: "MCO", Name: "Principality of Monaco", Type: "country"},
		{Code: "MDA", Name: "Republic of Moldova", Type: "country"},
		{Code: "MDG", Name: "Republic of Madagascar", Type: "country"},
		{Code: "MDV", Name: "Republic of Maldives", Type: "country"},
		{Code: "MEX", Name: "United Mexican States", Type: "country"},
		{Code: "MHL", Name: "Republic of the Marshall Islands", Type: "country"},
		{Code: "MKD", Name: "Republic of North Macedonia", Type: "country"},
		{Code: "MLI", Name: "Republic of Mali", Type: "country"},
		{Code: "MLT", Name: "Republic of Malta", Type: "country"},
		{Code: "MMR", Name: "Union of Burma", Type: "country"},
		{Code: "MNE", Name: "Montenegro", Type: "country"},
		{Code: "MNG", Name: "Mongolia", Type: "country"},
		{Code: "MNP", Name: "Commonwealth of the Northern Mariana Islands", Type: "country"},
		{Code: "MOZ", Name: "Republic of Mozambique", Type: "country"},
		{Code: "MRT", Name: "Islamic Republic of Mauritania", Type: "country"},
		{Code: "MSR", Name: "Montserrat", Type: "country"},
		{Code: "MTQ", Name: "Territorial Collectivity of Martinique", Type: "country"},
		{Code: "MUS", Name: "Republic of Mauritius", Type: "country"},
		{Code: "MWI", Name: "Republic of Malawi", Type: "country"},
		{Code: "MYS", Name: "Malaysia", Type: "country"},
		{Code: "MYT", Name: "Department of Mayotte", Type: "country"},
		{Code: "NAM", Name: "Republic of Namibia", Type: "country"},
		{Code: "NCL", Name: "New Caledonia", Type: "country"},
		{Code: "NER", Name: "Republic of Niger", Type: "country"},
		{Code: "NFK", Name: "Territory of Norfolk Island", Type: "country"},
		{Code: "NGA", Name: "Federal Republic of Nigeria", Type: "country"},
		{Code: "NIC", Name: "Republic of Nicaragua", Type: "country"},
		{Code: "NIU", Name: "Niue", Type: "country"},
		{Code: "NLD", Name: "Kingdom of the Netherlands", Type: "country"},
		{Code: "NOR", Name: "Kingdom of Norway", Type: "country"},
		{Code: "NPL", Name: "Federal Democratic Republic of Nepal", Type: "country"},
		{Code: "NRU", Name: "Republic of Nauru", Type: "country"},
		{Code: "NZL", Name: "New Zealand", Type: "country"},
		{Code: "OMN", Name: "Sultanate of Oman", Type: "country"},
		{Code: "PAK", Name: "Islamic Republic of Pakistan", Type: "country"},
		{Code: "PAN", Name: "Republic of Panama", Type: "country"},
		{Code: "PCN", Name: "Pitcairn, Henderson, Ducie, and Oeno Islands", Type: "country"},
		{Code: "PER", Name: "Republic of Peru", Type: "country"},
		{Code: "PHL", Name: "Republic of the Philippines", Type: "country"},
		{Code: "PLW", Name: "Republic of Palau", Type: "country"},
		{Code: "PNG", Name: "Independent State of Papua New Guinea", Type: "country"},
		{Code: "POL", Name: "Republic of Poland", Type: "country"},
		{Code: "PRI", Name: "Commonwealth of Puerto Rico", Type: "country"},
		{Code: "PRK", Name: "Democratic People's Republic of Korea", Type: "country"},
		{Code: "PRT", Name: "Portuguese Republic", Type: "country"},
		{Code: "PRY", Name: "Republic of Paraguay", Type: "country"},
		{Code: "PYF", Name: "French Polynesia", Type: "country"},
		{Code: "QAT", Name: "State of Qatar", Type: "country"},
		{Code: "REU", Name: "Region of Reunion", Type: "country"},
		{Code: "ROU", Name: "Romania", Type: "country"},
		{Code: "RUS", Name: "Russian Federation", Type: "country"},
		{Code: "RWA", Name: "Republic of Rwanda", Type: "country"},
		{Code: "SAU", Name: "Kingdom of Saudi Arabia", Type: "country"},
		{Code: "SDN", Name: "Republic of the Sudan", Type: "country"},
		{Code: "SEN", Name: "Republic of Senegal", Type: "country"},
		{Code: "SGP", Name: "Republic of Singapore", Type: "country"},
		{Code: "SGS", Name: "South Georgia and the South Sandwich Islands", Type: "country"},
		{Code: "SHN", Name: "Saint Helena, Ascension, and Tristan da Cunha", Type: "country"},
		{Code: "SLB", Name: "Solomon Islands", Type: "country"},
		{Code: "SLE", Name: "Republic of Sierra Leone", Type: "country"},
		{Code: "SLV", Name: "Republic of El Salvador", Type: "country"},
		{Code: "SMR", Name: "Republic of San Marino", Type: "country"},
		{Code: "SOM", Name: "Federal Republic of Somalia", Type: "country"},
		{Code: "SPM", Name: "Territorial Collectivity of Saint Pierre and Miquelon", Type: "country"},
		{Code: "SRB", Name: "Republic of Serbia", Type: "country"},
		{Code: "SSD", Name: "Republic of South Sudan", Type: "country"},
		{Code: "STP", Name: "Democratic Republic of Sao Tome and Principe", Type: "country"},
		{Code: "SUR", Name: "Republic of Suriname", Type: "country"},
		{Code: "SVK", Name: "Slovak Republic", Type: "country"},
		{Code: "SVN", Name: "Republic of Slovenia", Type: "country"},
		{Code: "SWE", Name: "Kingdom of Sweden", Type: "country"},
		{Code: "SWZ", Name: "Kingdom of Eswatini", Type: "country"},
		{Code: "SXM", Name: "Sint Maarten", Type: "country"},
		{Code: "SYC", Name: "Republic of Seychelles", Type: "country"},
		{Code: "SYR", Name: "Syrian Arab Republic", Type: "country"},
		{Code: "TCA", Name: "Turks and Caicos Islands", Type: "country"},
		{Code: "TCD", Name: "Republic of Chad", Type: "country"},
		{Code: "TGO", Name: "Togolese Republic", Type: "country"},
		{Code: "THA", Name: "Kingdom of Thailand", Type: "country"},
		{Code: "TJK", Name: "Republic of Tajikistan", Type: "country"},
		{Code: "TKL", Name: "Tokelau", Type: "country"},
		{Code: "TKM", Name: "Turkmenistan", Type: "country"},
		{Code: "TLS", Name: "Democratic Republic of Timor-Leste", Type: "country"},
		{Code: "TON", Name: "Kingdom of Tonga", Type: "country"},
		{Code: "TTO", Name: "Republic of Trinidad and Tobago", Type: "country"},
		{Code: "TUN", Name: "Republic of Tunisia", Type: "country"},
		{Code: "TUR", Name: "Republic of Turkey", Type: "country"},
		{Code: "TUV", Name: "Tuvalu", Type: "country"},
		{Code: "TWN", Name: "Taiwan", Type: "country"},
		{Code: "TZA", Name: "United Republic of Tanzania", Type: "country"},
		{Code: "UGA", Name: "Republic of Uganda", Type: "country"},
		{Code: "UKR", Name: "Ukraine", Type: "country"},
		{Code: "URY", Name: "Oriental Republic of Uruguay", Type: "country"},
		{Code: "USA", Name: "United States of America", Type: "country"},
		{Code: "UZB", Name: "Republic of Uzbekistan", Type: "country"},
		{Code: "VAT", Name: "State of the Vatican City", Type: "country"},
		{Code: "VCT", Name: "Saint Vincent and the Grenadines", Type: "country"},
		{Code: "VEN", Name: "Bolivarian Republic of Venezuela", Type: "country"},
		{Code: "VGB", Name: "British Virgin Islands", Type: "country"},
		{Code: "VIR", Name: "United States Virgin Islands", Type: "country"},
		{Code: "VNM", Name: "Socialist Republic of Vietnam", Type: "country"},
		{Code: "VUT", Name: "Republic of Vanuatu", Type: "country"},
		{Code: "WLF", Name: "Wallis and Futuna", Type: "country"},
		{Code: "WSM", Name: "Independent State of Samoa", Type: "country"},
		{Code: "XAC", Name: "Territory of Ashmore and Cartier Islands", Type: "country"},
		{Code: "XAZ", Name: "Entity 1", Type: "country"},
		{Code: "XBI", Name: "Bassas da India", Type: "country"},
		{Code: "XBK", Name: "Baker Island", Type: "country"},
		{Code: "XCR", Name: "Entity 2", Type: "country"},
		{Code: "XCS", Name: "Coral Sea Islands Territory", Type: "country"},
		{Code: "XCY", Name: "Entity 3", Type: "country"},
		{Code: "XEU", Name: "Europa Island", Type: "country"},
		{Code: "XGL", Name: "Glorioso Islands", Type: "country"},
		{Code: "XGZ", Name: "Gaza Strip", Type: "country"},
		{Code: "XHO", Name: "Howland Island", Type: "country"},
		{Code: "XJA", Name: "Johnston Atoll", Type: "country"},
		{Code: "XJM", Name: "Jan Mayen", Type: "country"},
		{Code: "XJN", Name: "Juan de Nova Island", Type: "country"},
		{Code: "XJV", Name: "Jarvis Island", Type: "country"},
		{Code: "XKM", Name: "Entity 4", Type: "country"},
		{Code: "XKN", Name: "Entity 5", Type: "country"},
		{Code: "XKR", Name: "Kingman Reef", Type: "country"},
		{Code: "XKS", Name: "Republic of Kosovo", Type: "country"},
		{Code: "XMW", Name: "Midway Islands", Type: "country"},
		{Code: "XNV", Name: "Navassa Island", Type: "country"},
		{Code: "XPL", Name: "Palmyra Atoll", Type: "country"},
		{Code: "XPR", Name: "Paracel Islands", Type: "country"},
		{Code: "XQZ", Name: "Akrotiri", Type: "country"},
		{Code: "XSP", Name: "Spratly Islands", Type: "country"},
		{Code: "XSV", Name: "Svalbard", Type: "country"},
		{Code: "XTR", Name: "Tromelin Island", Type: "country"},
		{Code: "XWB", Name: "West Bank", Type: "country"},
		{Code: "XWK", Name: "Wake Island", Type: "country"},
		{Code: "XXD", Name: "Dhekelia", Type: "country"},
		{Code: "YEM", Name: "Republic of Yemen", Type: "country"},
		{Code: "ZAF", Name: "Republic of South Africa", Type: "country"},
		{Code: "ZMB", Name: "Republic of Zambia", Type: "country"},
		{Code: "ZWE", Name: "Republic of Zimbabwe", Type: "country"},

		// Coalitions and organizations (IC Markings System Register)
		{Code: "ACGU", Name: "FOUR EYES", Type: "coalition"},
		{Code: "AMSP", Name: "AFRICOM Multinational Strategic Partners", Type: "coalition"},
		{Code: "AOSC", Name: "Athens Olympics Security Coalition", Type: "coalition"},
		{Code: "APFS", Name: "African Peacekeeping Force Somalia", Type: "coalition"},
		{Code: "ASEA", Name: "Association of Southeast Asian Nations (ASEAN)", Type: "coalition"},
		{Code: "AUSTRALIA_GROUP", Name: "Australia Group", Type: "coalition"},
		{Code: "BHTF", Name: "Boko Haram Task Force", Type: "coalition"},
		{Code: "BWCS", Name: "Biological Weapons Convention States", Type: "organization"},
		{Code: "CFCK", Name: "Combined Forces Command Korea", Type: "coalition"},
		{Code: "CFOD", Name: "Coalition Forces Odyssey Dawn", Type: "coalition"},
		{Code: "CFUP", Name: "Coalition Forces Unified Protector", Type: "coalition"},
		{Code: "CLFC", Name: "Combined Libya Fusion Cell", Type: "coalition"},
		{Code: "CMFC", Name: "Combined Maritime Forces Central", Type: "coalition"},
		{Code: "CMFP", Name: "Cooperative Maritime Forces Pacific", Type: "coalition"},
		{Code: "CPMT", Name: "Civilian Protection Monitoring Team for Sudan", Type: "coalition"},
		{Code: "CTOC", Name: "Countering Transnational Organized Crime", Type: "coalition"},
		{Code: "CWCS", Name: "Chemical Weapons Convention States", Type: "coalition"},
		{Code: "ECTF", Name: "European Counter-Terrorism Forces", Type: "coalition"},
		{Code: "EFOR", Name: "European Union Stabilization Forces in Bosnia", Type: "coalition"},
		{Code: "EU", Name: "European Union", Type: "coalition"},
		{Code: "EUDA", Name: "European Union DARFUR", Type: "coalition"},
		{Code: "FRME", Name: "Counter Violent Extremist Organizations Framework Partners", Type: "coalition"},
		{Code: "FVEY", Name: "FIVE EYES", Type: "coalition"},
		{Code: "GCCH", Name: "Gulf Cooperation Council", Type: "coalition"},
		{Code: "GCTF", Name: "Global Counter-Terrorism Forces", Type: "coalition"},
		{Code: "GFNX", Name: "Global Foreign Terrorist Fighter Network Exchange", Type: "coalition"},
		{Code: "GMIF", Name: "Global Maritime Interception Forces", Type: "coalition"},
		{Code: "IESC", Name: "International Events Security Coalition", Type: "coalition"},
		{Code: "IMSC", Name: "International Maritime Security Construct", Type: "coalition"},
		{Code: "IMSP", Name: "INDOPACOM Multinational Strategic Partners", Type: "coalition"},
		{Code: "IPMC", Name: "INDO PACIFIC Maritime Call", Type: "coalition"},
		{Code: "IRKS", Name: "Inherent Resolve Kinetic Support", Type: "coalition"},
		{Code: "ISAF", Name: "International Security Assistance Force for Afghanistan", Type: "coalition"},
		{Code: "ISSG", Name: "International Syria Support Group", Type: "coalition"},
		{Code: "KFOR", Name: "Stabilization Forces in Kosovo", Type: "coalition"},
		{Code: "MCFI", Name: "Multinational Coalition Forces-Iraq", Type: "coalition"},
		{Code: "MESF", Name: "Middle East Stability Force", Type: "coalition"},
		{Code: "MGEU", Name: "Multinational GEOINT Europe", Type: "coalition"},
		{Code: "MIFH", Name: "Multinational Interim Force Haiti", Type: "coalition"},
		{Code: "MLEC", Name: "Multi-Lateral Enduring Contingency", Type: "coalition"},
		{Code: "MNTF", Name: "Multinational Task Force", Type: "coalition"},
		{Code: "MPFL", Name: "Multinational Peacekeeping Forces", Type: "coalition"},
		{Code: "NACT", Name: "North African Counter-Terrorism Forces", Type: "coalition"},
		{Code: "NATO", Name: "North Atlantic Treaty Organization", Type: "organization"},
		{Code: "NCFE", Name: "NATO CFE Treaty on Conventional Armed Forces in Europe", Type: "coalition"},
		{Code: "NKIC", Name: "North Korea Intelligence Coalition", Type: "coalition"},
		{Code: "NRDC", Name: "NORDIC", Type: "coalition"},
		{Code: "NSG", Name: "Nuclear Suppliers' Group", Type: "coalition"},
		{Code: "OSAG", Name: "Olympic Security Advisory Group", Type: "coalition"},
		{Code: "OSTY", Name: "Open Skies Treaty", Type: "coalition"},
		{Code: "PAWA", Name: "Partnership for Actions in West Africa", Type: "coalition"},
		{Code: "PGMF", Name: "Persian Gulf Multinational Forces", Type: "coalition"},
		{Code: "PSMX", Name: "Pacific Security Monitoring Exchange", Type: "coalition"},
		{Code: "RISC", Name: "Russia Intelligence Sharing Coalition", Type: "coalition"},
		{Code: "RSMA", Name: "Resolute Support Mission Afghanistan", Type: "coalition"},
		{Code: "SFOR", Name: "Stabilization Force", Type: "coalition"},
		{Code: "SOFP", Name: "Special Operations Forces Partners", Type: "coalition"},
		{Code: "SPAA", Name: "SOF Planning Activities in Afghanistan (also called \"11-Eyes\")", Type: "coalition"},
		{Code: "TEYE", Name: "THREE EYES", Type: "coalition"},
		{Code: "TFTC", Name: "Terrorist Financing Targeting Center", Type: "coalition"},
		{Code: "UNCK", Name: "United Nations Command, Korea", Type: "coalition"},
	}
}
