package refdata

// CUICategories returns all supported CUI category markings.
// Specified categories (SP- prefix) require specific handling procedures defined
// by the authorizing law, regulation, or government-wide policy.
// Basic categories follow default CUI handling procedures.
func CUICategories() []CUICategory {
	return []CUICategory{
		// Specified categories (SP- prefix) — ordered alphabetically by base code.
		// Derived from CVEnumISMCUISpecified.xsd plus API extensions.
		{
			Code:        "SP-ADPO",
			Label:       "ADP Security-Related Information",
			Type:        "specified",
			Description: "Administrative data processing security information requiring specified handling procedures",
		},
		{
			Code:        "SP-AIV",
			Label:       "Agriculture Infrastructure Vulnerability",
			Type:        "specified",
			Description: "Agricultural critical infrastructure vulnerability assessments (7 CFR 331)",
		},
		{
			Code:        "SP-ARCHR",
			Label:       "Archaeological Resources",
			Type:        "specified",
			Description: "Information about archaeological resources protected under ARPA (16 U.S.C. §470hh)",
		},
		{
			Code:        "SP-BUDG",
			Label:       "Budget Information",
			Type:        "specified",
			Description: "Pre-decisional budget information protected under OMB Circular A-11",
		},
		{
			Code:        "SP-CCI",
			Label:       "Confidential Commercial Information",
			Type:        "specified",
			Description: "Trade secrets and commercial/financial information exempt from FOIA disclosure (5 U.S.C. §552(b)(4))",
		},
		{
			Code:        "SP-CEII",
			Label:       "Critical Energy Infrastructure Information",
			Type:        "specified",
			Description: "Information about critical energy infrastructure that could be useful to a person planning an attack on critical infrastructure (18 CFR 388.113)",
		},
		{
			Code:        "SP-CENS",
			Label:       "Census Information",
			Type:        "specified",
			Description: "Individual census records protected under Title 13 (13 U.S.C. §9)",
		},
		{
			Code:        "SP-CHLD",
			Label:       "Child Victim/Witness Information",
			Type:        "specified",
			Description: "Information identifying child victims or witnesses in federal cases (18 U.S.C. §3509)",
		},
		{
			Code:        "SP-CHRI",
			Label:       "Criminal History Record Information",
			Type:        "specified",
			Description: "Criminal history records disseminated under 28 CFR Part 20",
		},
		{
			Code:        "SP-CONTRACT",
			Label:       "Contractor Information",
			Type:        "specified",
			Description: "Source selection and contractor bid/proposal information (41 U.S.C. §2102)",
		},
		{
			Code:        "SP-CRITAN",
			Label:       "Critical Analysis",
			Type:        "specified",
			Description: "Analysis of critical infrastructure vulnerabilities and risks produced by DHS critical infrastructure analysis programs",
		},
		{
			Code:        "SP-CTI",
			Label:       "Controlled Technical Information",
			Type:        "specified",
			Description: "Military or space technology technical data with distribution limitations (DoD Instruction 5230.24)",
		},
		{
			Code:        "SP-CVI",
			Label:       "Chemical-terrorism Vulnerability Information",
			Type:        "specified",
			Description: "Information developed under the Chemical Facility Anti-Terrorism Standards (6 CFR Part 27)",
		},
		{
			Code:        "SP-DCNI",
			Label:       "DoD Critical Nuclear Weapon Design Information",
			Type:        "specified",
			Description: "Nuclear weapons design information requiring specified handling (10 U.S.C. §179)",
		},
		{
			Code:        "SP-EXPT",
			Label:       "Export Controlled Information",
			Type:        "specified",
			Description: "Unclassified information controlled under ITAR or EAR export regulations",
		},
		{
			Code:        "SP-FISA",
			Label:       "FISA Information",
			Type:        "specified",
			Description: "Foreign Intelligence Surveillance Act information (50 U.S.C. §1801 et seq.)",
		},
		{
			Code:        "SP-FISAB",
			Label:       "FISA Business Records",
			Type:        "specified",
			Description: "FISA business records orders information (50 U.S.C. §1861)",
		},
		{
			Code:        "SP-FNC",
			Label:       "Financial Records",
			Type:        "specified",
			Description: "Financial institution records protected under the Right to Financial Privacy Act (12 U.S.C. §3401)",
		},
		{
			Code:        "SP-FSEC",
			Label:       "Financial Security Information",
			Type:        "specified",
			Description: "Financial security data related to critical financial infrastructure protection",
		},
		{
			Code:        "SP-FUND",
			Label:       "Federal Funding Information",
			Type:        "specified",
			Description: "Federal grant and funding program information prior to public release",
		},
		{
			Code:        "SP-GENETIC",
			Label:       "Genetic Information",
			Type:        "specified",
			Description: "Genetic information protected under the Genetic Information Nondiscrimination Act (42 U.S.C. §2000ff)",
		},
		{
			Code:        "SP-GEO",
			Label:       "Geodetic Product Information",
			Type:        "specified",
			Description: "Geodetic survey and mapping data with restricted distribution",
		},
		{
			Code:        "SP-HISTP",
			Label:       "Historic Properties",
			Type:        "specified",
			Description: "Information about historic properties locations protected under the NHPA (54 U.S.C. §307103)",
		},
		{
			Code:        "SP-HLTH",
			Label:       "Health Information",
			Type:        "specified",
			Description: "Protected health information under HIPAA (45 CFR Parts 160 and 164)",
		},
		{
			Code:        "SP-ID",
			Label:       "Identification Information",
			Type:        "specified",
			Description: "Personally identifying information in federal records requiring specified handling",
		},
		{
			Code:        "SP-IFNC",
			Label:       "International Financial Institutions",
			Type:        "specified",
			Description: "International financial institution supervisory information (22 U.S.C. §286f)",
		},
		{
			Code:        "SP-INF",
			Label:       "Infrastructure Information",
			Type:        "specified",
			Description: "Sensitive infrastructure information requiring specified handling procedures",
		},
		{
			Code:        "SP-INTEL",
			Label:       "Intelligence Information",
			Type:        "specified",
			Description: "Intelligence sources and methods information requiring specified handling",
		},
		{
			Code:        "SP-INTL",
			Label:       "International Agreement Information",
			Type:        "specified",
			Description: "Information controlled under international agreements and treaties",
		},
		{
			Code:        "SP-INV",
			Label:       "Investigation Information",
			Type:        "specified",
			Description: "Law enforcement investigation and informant records (5 U.S.C. §552a(j)(2))",
		},
		{
			Code:        "SP-JURY",
			Label:       "Grand Jury Information",
			Type:        "specified",
			Description: "Federal grand jury information protected under FRCP Rule 6(e)",
		},
		{
			Code:        "SP-LDNA",
			Label:       "Law Enforcement DNA",
			Type:        "specified",
			Description: "DNA identification records maintained by the FBI under 34 U.S.C. §12592",
		},
		{
			Code:        "SP-LFNC",
			Label:       "Legal-Financial Records",
			Type:        "specified",
			Description: "Legal financial information in regulatory proceedings requiring specified handling",
		},
		{
			Code:        "SP-LPROT",
			Label:       "Legal Privilege/Protection",
			Type:        "specified",
			Description: "Legally privileged information including attorney-client and work product protections",
		},
		{
			Code:        "SP-MFC",
			Label:       "Military Flight Clearance",
			Type:        "specified",
			Description: "Military aircraft flight clearance and routing information",
		},
		{
			Code:        "SP-NNPI",
			Label:       "Naval Nuclear Propulsion Information",
			Type:        "specified",
			Description: "Naval nuclear propulsion technical data controlled under 42 U.S.C. §2168",
		},
		{
			Code:        "SP-NPSR",
			Label:       "Nuclear Power Safety Related",
			Type:        "specified",
			Description: "Nuclear safety-related information for power plants (10 CFR 73.21)",
		},
		{
			Code:        "SP-NUC",
			Label:       "Nuclear Information",
			Type:        "specified",
			Description: "General nuclear-related information not covered by specific nuclear categories",
		},
		{
			Code:        "SP-PCII",
			Label:       "Protected Critical Infrastructure Information",
			Type:        "specified",
			Description: "Voluntarily submitted critical infrastructure information validated under the PCII Program (6 CFR Part 29)",
		},
		{
			Code:        "SP-PERS",
			Label:       "Personnel Records",
			Type:        "specified",
			Description: "Federal personnel records protected under the Privacy Act (5 U.S.C. §552a)",
		},
		{
			Code:        "SP-PHYS",
			Label:       "Physical Security (Specified)",
			Type:        "specified",
			Description: "Specified physical security information requiring enhanced handling under authorizing directive",
		},
		{
			Code:        "SP-PRIIG",
			Label:       "Privacy Inspector General",
			Type:        "specified",
			Description: "Inspector General investigation records involving privacy data",
		},
		{
			Code:        "SP-PROCURE",
			Label:       "Procurement Information",
			Type:        "specified",
			Description: "Federal acquisition and procurement sensitive information (FAR 3.104)",
		},
		{
			Code:        "SP-PROPIN",
			Label:       "Proprietary Business Information",
			Type:        "specified",
			Description: "Proprietary business and trade secret information submitted to the government",
		},
		{
			Code:        "SP-PRVCY",
			Label:       "Privacy Information",
			Type:        "specified",
			Description: "Personally identifiable information protected under the Privacy Act (5 U.S.C. §552a)",
		},
		{
			Code:        "SP-SGI",
			Label:       "Safeguards Information",
			Type:        "specified",
			Description: "Nuclear facility safeguards information under 10 CFR 73.21",
		},
		{
			Code:        "SP-SRI",
			Label:       "Statistical Registration Information",
			Type:        "specified",
			Description: "Statistical registration data with restricted use (44 U.S.C. §3501)",
		},
		{
			Code:        "SP-SSEL",
			Label:       "Selectee/No-Fly List",
			Type:        "specified",
			Description: "Transportation security selectee and no-fly list information (49 U.S.C. §114(s))",
		},
		{
			Code:        "SP-SSI",
			Label:       "Sensitive Security Information",
			Type:        "specified",
			Description: "Transportation security information protected under 49 CFR Part 1520",
		},
		{
			Code:        "SP-STAT",
			Label:       "Statistical Information",
			Type:        "specified",
			Description: "Statistical data collected under a pledge of confidentiality (CIPSEA)",
		},
		{
			Code:        "SP-STUD",
			Label:       "Student Records",
			Type:        "specified",
			Description: "Educational records protected under FERPA (20 U.S.C. §1232g)",
		},
		{
			Code:        "SP-SUB",
			Label:       "Subcontract Information",
			Type:        "specified",
			Description: "Subcontractor proposal and pricing information (FAR 15.207)",
		},
		{
			Code:        "SP-TAX",
			Label:       "Federal Taxpayer Information",
			Type:        "specified",
			Description: "Tax return and return information protected under 26 U.S.C. §6103",
		},
		{
			Code:        "SP-TSCA",
			Label:       "Toxic Substances Control Act",
			Type:        "specified",
			Description: "Chemical data submitted under TSCA with restrictions on disclosure (15 U.S.C. §2613)",
		},
		{
			Code:        "SP-UCNI",
			Label:       "Unclassified Controlled Nuclear Information",
			Type:        "specified",
			Description: "DoE unclassified nuclear information controlled under 10 CFR 1017",
		},
		{
			Code:        "SP-WDT",
			Label:       "Weapons Data and Technology",
			Type:        "specified",
			Description: "Weapons system technical data with distribution limitations",
		},
		{
			Code:        "SP-WHSTL",
			Label:       "Whistleblower Protection",
			Type:        "specified",
			Description: "Whistleblower identity and disclosure information (5 U.S.C. §1213)",
		},
		{
			Code:        "SP-WIT",
			Label:       "Witness Protection",
			Type:        "specified",
			Description: "Federal witness protection program information (18 U.S.C. §3521)",
		},

		// Basic categories — ordered alphabetically
		{
			Code:        "CRIT",
			Label:       "Critical Infrastructure",
			Type:        "basic",
			Description: "General critical infrastructure information not covered by a specified CUI category",
		},
		{
			Code:        "EMGT",
			Label:       "Emergency Management",
			Type:        "basic",
			Description: "Information related to emergency management planning, response, or recovery operations",
		},
		{
			Code:        "ISVI",
			Label:       "Infrastructure Security Vulnerability Information",
			Type:        "basic",
			Description: "Information about vulnerabilities in critical infrastructure systems",
		},
		{
			Code:        "PHYS",
			Label:       "Physical Security",
			Type:        "basic",
			Description: "Information related to physical security measures, plans, or assessments",
		},
		{
			Code:        "SAFE",
			Label:       "Safety",
			Type:        "basic",
			Description: "Information related to safety conditions, incidents, or protective measures",
		},
		{
			Code:        "WATER",
			Label:       "Water Assessments",
			Type:        "basic",
			Description: "Information about water system vulnerability assessments and security measures",
		},
	}
}
